### ISSUE TITLE
Decoding of input data failed.

### ISSUE THREAD

**Issue by joneqing** [imagemin/cwebp-bin#13]
I have got this error: 
  events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: IWICImagingFactory_CreateDecoderFromStream( factory, stream, NULL, WICDecodeMetadataCacheOnDemand, &decoder) failed 88982f50
Decoding of input data failed.
Status: 2(INVALID_PARAM)
Error! Could not process file -
Error! Cannot read input picture file '-'

    at ChildProcess.<anonymous> (D:\programing\www\imageConverter\node_modules\imagemin-webp\index.js:93:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
when i have a pic named 'lo_go.png'.

**Comment by kode8** [comment]
I get this was well

**Comment by rere3091** [comment]
I have the same error, what is the solution please ?
Thank's
