### ISSUE TITLE
cwebp-bin@7.0.1 postinstall: `node lib/install.js`

### ISSUE THREAD

**Issue by HeMin0919** [imagemin/cwebp-bin#57]
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\vue3Test\hello-vue3\node_modules\cwebp-bin\lib\install.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by Christopher-Hayes** [comment]
Reverting to v6.1.2 fixes this issue for me.

Probably related to #54
